import { AdverseeventActuality } from "./AdverseeventActuality";
import { AdverseEvent_SuspectEntity } from "./AdverseEvent_SuspectEntity";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";

export interface AdverseEvent {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier | null | undefined;
    actuality: AdverseeventActuality | null | undefined;
    category: CodeableConcept[] | null | undefined;
    event: CodeableConcept | null | undefined;
    subject: Reference;
    encounter: Reference | null | undefined;
    date: dateTime | null | undefined;
    detected: dateTime | null | undefined;
    recordedDate: dateTime | null | undefined;
    resultingCondition: Reference[] | null | undefined;
    location: Reference | null | undefined;
    seriousness: CodeableConcept | null | undefined;
    severity: CodeableConcept | null | undefined;
    outcome: CodeableConcept | null | undefined;
    recorder: Reference | null | undefined;
    contributor: Reference[] | null | undefined;
    suspectEntity: AdverseEvent_SuspectEntity[] | null | undefined;
    subjectMedicalHistory: Reference[] | null | undefined;
    referenceDocument: Reference[] | null | undefined;
    study: Reference[] | null | undefined;
}
