import { Annotation } from "./Annotation";
import { canonical } from "./canonical";
import { ChargeitemStatus } from "./ChargeitemStatus";
import { ChargeItem_Performer } from "./ChargeItem_Performer";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { decimal } from "./decimal";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Money } from "./Money";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { Quantity } from "./Quantity";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { Timing } from "./Timing";
import { uri } from "./uri";

export interface ChargeItem {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    definitionUri: uri[] | null | undefined;
    definitionCanonical: canonical[] | null | undefined;
    status: ChargeitemStatus | null | undefined;
    partOf: Reference[] | null | undefined;
    code: CodeableConcept;
    subject: Reference;
    context: Reference | null | undefined;
    occurrenceDateTime: string | null | undefined;
    occurrencePeriod: Period | null | undefined;
    occurrenceTiming: Timing | null | undefined;
    performer: ChargeItem_Performer[] | null | undefined;
    performingOrganization: Reference | null | undefined;
    requestingOrganization: Reference | null | undefined;
    costCenter: Reference | null | undefined;
    quantity: Quantity | null | undefined;
    bodysite: CodeableConcept[] | null | undefined;
    factorOverride: decimal | null | undefined;
    priceOverride: Money | null | undefined;
    overrideReason: string | null | undefined;
    enterer: Reference | null | undefined;
    enteredDate: dateTime | null | undefined;
    reason: CodeableConcept[] | null | undefined;
    service: Reference[] | null | undefined;
    productReference: Reference | null | undefined;
    productCodeableConcept: CodeableConcept | null | undefined;
    account: Reference[] | null | undefined;
    note: Annotation[] | null | undefined;
    supportingInformation: Reference[] | null | undefined;
}
