import { Annotation } from "./Annotation";
import { canonical } from "./canonical";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Reference } from "./Reference";
import { RequestGroup_Action } from "./RequestGroup_Action";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";

export interface RequestGroup {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    instantiatesCanonical: canonical[] | null | undefined;
    instantiatesUri: uri[] | null | undefined;
    basedOn: Reference[] | null | undefined;
    replaces: Reference[] | null | undefined;
    groupIdentifier: Identifier | null | undefined;
    status: code | null | undefined;
    intent: code | null | undefined;
    priority: code | null | undefined;
    code: CodeableConcept | null | undefined;
    subject: Reference | null | undefined;
    encounter: Reference | null | undefined;
    authoredOn: dateTime | null | undefined;
    author: Reference | null | undefined;
    reasonCode: CodeableConcept[] | null | undefined;
    reasonReference: Reference[] | null | undefined;
    note: Annotation[] | null | undefined;
    action: RequestGroup_Action[] | null | undefined;
}
