import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { date } from "./date";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { Timing } from "./Timing";
import { uri } from "./uri";
import { VerificationResult_Attestation } from "./VerificationResult_Attestation";
import { VerificationResult_PrimarySource } from "./VerificationResult_PrimarySource";
import { VerificationResult_Validator } from "./VerificationResult_Validator";

export interface VerificationResult {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    target: Reference[] | null | undefined;
    targetLocation: string[] | null | undefined;
    need: CodeableConcept | null | undefined;
    status: code | null | undefined;
    statusDate: dateTime | null | undefined;
    validationType: CodeableConcept | null | undefined;
    validationProcess: CodeableConcept[] | null | undefined;
    frequency: Timing | null | undefined;
    lastPerformed: dateTime | null | undefined;
    nextScheduled: date | null | undefined;
    failureAction: CodeableConcept | null | undefined;
    primarySource: VerificationResult_PrimarySource[] | null | undefined;
    attestation: VerificationResult_Attestation | null | undefined;
    validator: VerificationResult_Validator[] | null | undefined;
}
