import { AppointmentStatus } from "./AppointmentStatus";
import { Appointment_Participant } from "./Appointment_Participant";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { instant } from "./instant";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { positiveInt } from "./positiveInt";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { unsignedInt } from "./unsignedInt";
import { uri } from "./uri";

export interface Appointment {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: AppointmentStatus | null | undefined;
    cancelationReason: CodeableConcept | null | undefined;
    serviceCategory: CodeableConcept[] | null | undefined;
    serviceType: CodeableConcept[] | null | undefined;
    specialty: CodeableConcept[] | null | undefined;
    appointmentType: CodeableConcept | null | undefined;
    reasonCode: CodeableConcept[] | null | undefined;
    reasonReference: Reference[] | null | undefined;
    priority: unsignedInt | null | undefined;
    description: string | null | undefined;
    supportingInformation: Reference[] | null | undefined;
    start: instant | null | undefined;
    end: instant | null | undefined;
    minutesDuration: positiveInt | null | undefined;
    slot: Reference[] | null | undefined;
    created: dateTime | null | undefined;
    comment: string | null | undefined;
    patientInstruction: string | null | undefined;
    basedOn: Reference[] | null | undefined;
    participant: Appointment_Participant[];
    requestedPeriod: Period[] | null | undefined;
}
