import { Attachment } from "./Attachment";
import { ClaimResponse_AddItem } from "./ClaimResponse_AddItem";
import { ClaimResponse_Adjudication } from "./ClaimResponse_Adjudication";
import { ClaimResponse_Error } from "./ClaimResponse_Error";
import { ClaimResponse_Insurance } from "./ClaimResponse_Insurance";
import { ClaimResponse_Item } from "./ClaimResponse_Item";
import { ClaimResponse_Payment } from "./ClaimResponse_Payment";
import { ClaimResponse_ProcessNote } from "./ClaimResponse_ProcessNote";
import { ClaimResponse_Total } from "./ClaimResponse_Total";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";

export interface ClaimResponse {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: code | null | undefined;
    type: CodeableConcept;
    subType: CodeableConcept | null | undefined;
    use: code | null | undefined;
    patient: Reference;
    created: dateTime | null | undefined;
    insurer: Reference;
    requestor: Reference | null | undefined;
    request: Reference | null | undefined;
    outcome: code | null | undefined;
    disposition: string | null | undefined;
    preAuthRef: string | null | undefined;
    preAuthPeriod: Period | null | undefined;
    payeeType: CodeableConcept | null | undefined;
    item: ClaimResponse_Item[] | null | undefined;
    addItem: ClaimResponse_AddItem[] | null | undefined;
    adjudication: ClaimResponse_Adjudication[] | null | undefined;
    total: ClaimResponse_Total[] | null | undefined;
    payment: ClaimResponse_Payment | null | undefined;
    fundsReserve: CodeableConcept | null | undefined;
    formCode: CodeableConcept | null | undefined;
    form: Attachment | null | undefined;
    processNote: ClaimResponse_ProcessNote[] | null | undefined;
    communicationRequest: Reference[] | null | undefined;
    insurance: ClaimResponse_Insurance[] | null | undefined;
    error: ClaimResponse_Error[] | null | undefined;
}
