import { Attachment } from "./Attachment";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { ConsentStatus } from "./ConsentStatus";
import { Consent_Policy } from "./Consent_Policy";
import { Consent_Provision } from "./Consent_Provision";
import { Consent_Verification } from "./Consent_Verification";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";

export interface Consent {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: ConsentStatus | null | undefined;
    scope: CodeableConcept;
    category: CodeableConcept[];
    patient: Reference | null | undefined;
    dateTime: dateTime | null | undefined;
    performer: Reference[] | null | undefined;
    organization: Reference[] | null | undefined;
    sourceAttachment: Attachment | null | undefined;
    sourceReference: Reference | null | undefined;
    policy: Consent_Policy[] | null | undefined;
    policyRule: CodeableConcept | null | undefined;
    verification: Consent_Verification[] | null | undefined;
    provision: Consent_Provision | null | undefined;
}
