import { Attachment } from "./Attachment";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { ExplanationofbenefitStatus } from "./ExplanationofbenefitStatus";
import { ExplanationOfBenefit_Accident } from "./ExplanationOfBenefit_Accident";
import { ExplanationOfBenefit_AddItem } from "./ExplanationOfBenefit_AddItem";
import { ExplanationOfBenefit_Adjudication } from "./ExplanationOfBenefit_Adjudication";
import { ExplanationOfBenefit_BenefitBalance } from "./ExplanationOfBenefit_BenefitBalance";
import { ExplanationOfBenefit_CareTeam } from "./ExplanationOfBenefit_CareTeam";
import { ExplanationOfBenefit_Diagnosis } from "./ExplanationOfBenefit_Diagnosis";
import { ExplanationOfBenefit_Insurance } from "./ExplanationOfBenefit_Insurance";
import { ExplanationOfBenefit_Item } from "./ExplanationOfBenefit_Item";
import { ExplanationOfBenefit_Payee } from "./ExplanationOfBenefit_Payee";
import { ExplanationOfBenefit_Payment } from "./ExplanationOfBenefit_Payment";
import { ExplanationOfBenefit_Procedure } from "./ExplanationOfBenefit_Procedure";
import { ExplanationOfBenefit_ProcessNote } from "./ExplanationOfBenefit_ProcessNote";
import { ExplanationOfBenefit_Related } from "./ExplanationOfBenefit_Related";
import { ExplanationOfBenefit_SupportingInfo } from "./ExplanationOfBenefit_SupportingInfo";
import { ExplanationOfBenefit_Total } from "./ExplanationOfBenefit_Total";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { positiveInt } from "./positiveInt";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";

export interface ExplanationOfBenefit {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: ExplanationofbenefitStatus | null | undefined;
    type: CodeableConcept;
    subType: CodeableConcept | null | undefined;
    use: code | null | undefined;
    patient: Reference;
    billablePeriod: Period | null | undefined;
    created: dateTime | null | undefined;
    enterer: Reference | null | undefined;
    insurer: Reference;
    provider: Reference;
    priority: CodeableConcept | null | undefined;
    fundsReserveRequested: CodeableConcept | null | undefined;
    fundsReserve: CodeableConcept | null | undefined;
    related: ExplanationOfBenefit_Related[] | null | undefined;
    prescription: Reference | null | undefined;
    originalPrescription: Reference | null | undefined;
    payee: ExplanationOfBenefit_Payee | null | undefined;
    referral: Reference | null | undefined;
    facility: Reference | null | undefined;
    claim: Reference | null | undefined;
    claimResponse: Reference | null | undefined;
    outcome: code | null | undefined;
    disposition: string | null | undefined;
    preAuthRef: string[] | null | undefined;
    preAuthRefPeriod: Period[] | null | undefined;
    careTeam: ExplanationOfBenefit_CareTeam[] | null | undefined;
    supportingInfo: ExplanationOfBenefit_SupportingInfo[] | null | undefined;
    diagnosis: ExplanationOfBenefit_Diagnosis[] | null | undefined;
    procedure: ExplanationOfBenefit_Procedure[] | null | undefined;
    precedence: positiveInt | null | undefined;
    insurance: ExplanationOfBenefit_Insurance[];
    accident: ExplanationOfBenefit_Accident | null | undefined;
    item: ExplanationOfBenefit_Item[] | null | undefined;
    addItem: ExplanationOfBenefit_AddItem[] | null | undefined;
    adjudication: ExplanationOfBenefit_Adjudication[] | null | undefined;
    total: ExplanationOfBenefit_Total[] | null | undefined;
    payment: ExplanationOfBenefit_Payment | null | undefined;
    formCode: CodeableConcept | null | undefined;
    form: Attachment | null | undefined;
    processNote: ExplanationOfBenefit_ProcessNote[] | null | undefined;
    benefitPeriod: Period | null | undefined;
    benefitBalance: ExplanationOfBenefit_BenefitBalance[] | null | undefined;
}
