import { Address } from "./Address";
import { Attachment } from "./Attachment";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { ContactPoint } from "./ContactPoint";
import { date } from "./date";
import { Extension } from "./Extension";
import { HumanName } from "./HumanName";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { Reference } from "./Reference";
import { RelatedpersonGender } from "./RelatedpersonGender";
import { RelatedPerson_Communication } from "./RelatedPerson_Communication";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";

export interface RelatedPerson {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    active: boolean | null | undefined;
    patient: Reference;
    relationship: CodeableConcept[] | null | undefined;
    name: HumanName[] | null | undefined;
    telecom: ContactPoint[] | null | undefined;
    gender: RelatedpersonGender | null | undefined;
    birthDate: date | null | undefined;
    address: Address[] | null | undefined;
    photo: Attachment[] | null | undefined;
    period: Period | null | undefined;
    communication: RelatedPerson_Communication[] | null | undefined;
}
