import { Annotation } from "./Annotation";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { RiskAssessment_Prediction } from "./RiskAssessment_Prediction";
import { uri } from "./uri";

export interface RiskAssessment {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    basedOn: Reference | null | undefined;
    parent: Reference | null | undefined;
    status: code | null | undefined;
    method: CodeableConcept | null | undefined;
    code: CodeableConcept | null | undefined;
    subject: Reference;
    encounter: Reference | null | undefined;
    occurrenceDateTime: string | null | undefined;
    occurrencePeriod: Period | null | undefined;
    condition: Reference | null | undefined;
    performer: Reference | null | undefined;
    reasonCode: CodeableConcept[] | null | undefined;
    reasonReference: Reference[] | null | undefined;
    basis: Reference[] | null | undefined;
    prediction: RiskAssessment_Prediction[] | null | undefined;
    mitigation: string | null | undefined;
    note: Annotation[] | null | undefined;
}
