import { ClaimUse } from "./ClaimUse";
import { Claim_Accident } from "./Claim_Accident";
import { Claim_CareTeam } from "./Claim_CareTeam";
import { Claim_Diagnosis } from "./Claim_Diagnosis";
import { Claim_Insurance } from "./Claim_Insurance";
import { Claim_Item } from "./Claim_Item";
import { Claim_Payee } from "./Claim_Payee";
import { Claim_Procedure } from "./Claim_Procedure";
import { Claim_Related } from "./Claim_Related";
import { Claim_SupportingInfo } from "./Claim_SupportingInfo";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Money } from "./Money";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";
export interface Claim {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: code | null | undefined;
    type: CodeableConcept;
    subType: CodeableConcept | null | undefined;
    use: ClaimUse | null | undefined;
    patient: Reference;
    billablePeriod: Period | null | undefined;
    created: dateTime | null | undefined;
    enterer: Reference | null | undefined;
    insurer: Reference | null | undefined;
    provider: Reference;
    priority: CodeableConcept;
    fundsReserve: CodeableConcept | null | undefined;
    related: Claim_Related[] | null | undefined;
    prescription: Reference | null | undefined;
    originalPrescription: Reference | null | undefined;
    payee: Claim_Payee | null | undefined;
    referral: Reference | null | undefined;
    facility: Reference | null | undefined;
    careTeam: Claim_CareTeam[] | null | undefined;
    supportingInfo: Claim_SupportingInfo[] | null | undefined;
    diagnosis: Claim_Diagnosis[] | null | undefined;
    procedure: Claim_Procedure[] | null | undefined;
    insurance: Claim_Insurance[];
    accident: Claim_Accident | null | undefined;
    item: Claim_Item[] | null | undefined;
    total: Money | null | undefined;
}
