import { Annotation } from "./Annotation";
import { ClinicalImpression_Finding } from "./ClinicalImpression_Finding";
import { ClinicalImpression_Investigation } from "./ClinicalImpression_Investigation";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Period } from "./Period";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";
export interface ClinicalImpression {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: code | null | undefined;
    statusReason: CodeableConcept | null | undefined;
    code: CodeableConcept | null | undefined;
    description: string | null | undefined;
    subject: Reference;
    encounter: Reference | null | undefined;
    effectiveDateTime: string | null | undefined;
    effectivePeriod: Period | null | undefined;
    date: dateTime | null | undefined;
    assessor: Reference | null | undefined;
    previous: Reference | null | undefined;
    problem: Reference[] | null | undefined;
    investigation: ClinicalImpression_Investigation[] | null | undefined;
    protocol: uri[] | null | undefined;
    summary: string | null | undefined;
    finding: ClinicalImpression_Finding[] | null | undefined;
    prognosisCodeableConcept: CodeableConcept[] | null | undefined;
    prognosisReference: Reference[] | null | undefined;
    supportingInfo: Reference[] | null | undefined;
    note: Annotation[] | null | undefined;
}
