import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { DocumentreferenceStatus } from "./DocumentreferenceStatus";
import { DocumentReference_Content } from "./DocumentReference_Content";
import { DocumentReference_Context } from "./DocumentReference_Context";
import { DocumentReference_RelatesTo } from "./DocumentReference_RelatesTo";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { instant } from "./instant";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";
export interface DocumentReference {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    masterIdentifier: Identifier | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: DocumentreferenceStatus | null | undefined;
    docStatus: code | null | undefined;
    type: CodeableConcept | null | undefined;
    category: CodeableConcept[] | null | undefined;
    subject: Reference | null | undefined;
    date: instant | null | undefined;
    author: Reference[] | null | undefined;
    authenticator: Reference | null | undefined;
    custodian: Reference | null | undefined;
    relatesTo: DocumentReference_RelatesTo[] | null | undefined;
    description: string | null | undefined;
    securityLabel: CodeableConcept[] | null | undefined;
    content: DocumentReference_Content[];
    context: DocumentReference_Context | null | undefined;
}
