import { Annotation } from "./Annotation";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { date } from "./date";
import { Extension } from "./Extension";
import { GoalLifecyclestatus } from "./GoalLifecyclestatus";
import { Goal_Target } from "./Goal_Target";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";
export interface Goal {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    lifecycleStatus: GoalLifecyclestatus | null | undefined;
    achievementStatus: CodeableConcept | null | undefined;
    category: CodeableConcept[] | null | undefined;
    priority: CodeableConcept | null | undefined;
    description: CodeableConcept;
    subject: Reference;
    startDate: string | null | undefined;
    startCodeableConcept: CodeableConcept | null | undefined;
    target: Goal_Target[] | null | undefined;
    statusDate: date | null | undefined;
    statusReason: string | null | undefined;
    expressedBy: Reference | null | undefined;
    addresses: Reference[] | null | undefined;
    note: Annotation[] | null | undefined;
    outcomeCode: CodeableConcept[] | null | undefined;
    outcomeReference: Reference[] | null | undefined;
}
