import { Annotation } from "./Annotation";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { Coding } from "./Coding";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { ImagingstudyStatus } from "./ImagingstudyStatus";
import { ImagingStudy_Series } from "./ImagingStudy_Series";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { unsignedInt } from "./unsignedInt";
import { uri } from "./uri";
export interface ImagingStudy {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: ImagingstudyStatus | null | undefined;
    modality: Coding[] | null | undefined;
    subject: Reference;
    encounter: Reference | null | undefined;
    started: dateTime | null | undefined;
    basedOn: Reference[] | null | undefined;
    referrer: Reference | null | undefined;
    interpreter: Reference[] | null | undefined;
    endpoint: Reference[] | null | undefined;
    numberOfSeries: unsignedInt | null | undefined;
    numberOfInstances: unsignedInt | null | undefined;
    procedureReference: Reference | null | undefined;
    procedureCode: CodeableConcept[] | null | undefined;
    location: Reference | null | undefined;
    reasonCode: CodeableConcept[] | null | undefined;
    reasonReference: Reference[] | null | undefined;
    note: Annotation[] | null | undefined;
    description: string | null | undefined;
    series: ImagingStudy_Series[] | null | undefined;
}
