import { Annotation } from "./Annotation";
import { code } from "./code";
import { CodeableConcept } from "./CodeableConcept";
import { date } from "./date";
import { dateTime } from "./dateTime";
import { Extension } from "./Extension";
import { id } from "./id";
import { Identifier } from "./Identifier";
import { Immunization_Education } from "./Immunization_Education";
import { Immunization_Performer } from "./Immunization_Performer";
import { Immunization_ProtocolApplied } from "./Immunization_ProtocolApplied";
import { Immunization_Reaction } from "./Immunization_Reaction";
import { Meta } from "./Meta";
import { Narrative } from "./Narrative";
import { Quantity } from "./Quantity";
import { Reference } from "./Reference";
import { ResourceList } from "./ResourceList";
import { uri } from "./uri";
export interface Immunization {
    resourceType: string;
    id: id | null | undefined;
    meta: Meta | null | undefined;
    implicitRules: uri | null | undefined;
    language: code | null | undefined;
    text: Narrative | null | undefined;
    contained: ResourceList[] | null | undefined;
    extension: Extension[] | null | undefined;
    modifierExtension: Extension[] | null | undefined;
    identifier: Identifier[] | null | undefined;
    status: code | null | undefined;
    statusReason: CodeableConcept | null | undefined;
    vaccineCode: CodeableConcept;
    patient: Reference;
    encounter: Reference | null | undefined;
    occurrenceDateTime: string | null | undefined;
    occurrenceString: string | null | undefined;
    recorded: dateTime | null | undefined;
    primarySource: boolean | null | undefined;
    reportOrigin: CodeableConcept | null | undefined;
    location: Reference | null | undefined;
    manufacturer: Reference | null | undefined;
    lotNumber: string | null | undefined;
    expirationDate: date | null | undefined;
    site: CodeableConcept | null | undefined;
    route: CodeableConcept | null | undefined;
    doseQuantity: Quantity | null | undefined;
    performer: Immunization_Performer[] | null | undefined;
    note: Annotation[] | null | undefined;
    reasonCode: CodeableConcept[] | null | undefined;
    reasonReference: Reference[] | null | undefined;
    isSubpotent: boolean | null | undefined;
    subpotentReason: CodeableConcept[] | null | undefined;
    education: Immunization_Education[] | null | undefined;
    programEligibility: CodeableConcept[] | null | undefined;
    fundingSource: CodeableConcept | null | undefined;
    reaction: Immunization_Reaction[] | null | undefined;
    protocolApplied: Immunization_ProtocolApplied[] | null | undefined;
}
